window.mockReports = [
    {
        id: "RPT-001",
        reportName: "FedNow Daily Activity Summary",
        description: "Aggregate summary of all FedNow transactions processed today, including settled, rejected, and pending.",
        author: "Rahul Mehta",
        visibility: "public",
        category: "Payment Transactions",
        paymentRail: "FedNow",
        regulatoryBody: "Federal Reserve",
        region: "US",
        frequency: "Daily",
        reportStatus: "published",
        version: "1.0",
        createdAt: "2026-07-01T08:00:00Z",
        updatedAt: "2026-07-20T10:00:00Z",
        tags: ["FedNow", "Daily", "Summary"],
        dataset: "Payment Transactions",
        schedule: { type: "Scheduled", frequency: "Daily", startDate: "2026-07-01", runTime: "18:00", timezone: "EST", delivery: "Download", retention: "30 days" },
        filters: [],
        selectedFields: ["transaction_id", "amount", "status", "rail"]
    },
    {
        id: "RPT-002",
        reportName: "SEPA SCT Exceptions",
        description: "List of all SEPA Credit Transfer exceptions requiring manual intervention or repair.",
        author: "Ananya Sharma",
        visibility: "public",
        category: "Exceptions",
        paymentRail: "SEPA SCT",
        regulatoryBody: "EPC",
        region: "Europe",
        frequency: "Hourly",
        reportStatus: "published",
        version: "2.1",
        createdAt: "2026-07-15T09:30:00Z",
        updatedAt: "2026-07-21T11:15:00Z",
        tags: ["SEPA", "Exceptions", "Hourly"],
        dataset: "Exceptions",
        schedule: { type: "Scheduled", frequency: "Hourly", startDate: "2026-07-15", runTime: "00:00", timezone: "CET", delivery: "Save to Report Center", retention: "60 days" },
        filters: [],
        selectedFields: ["exception_id", "transaction_id", "reason_code", "amount", "currency"]
    },
    {
        id: "RPT-003",
        reportName: "Fedwire Monthly High-Value",
        description: "Detailed breakdown of Fedwire transfers exceeding $1M for liquidity monitoring.",
        author: "Michael Carter",
        visibility: "private",
        category: "Payment Transactions",
        paymentRail: "Fedwire",
        regulatoryBody: "Federal Reserve",
        region: "US",
        frequency: "Monthly",
        reportStatus: "published",
        version: "1.2",
        createdAt: "2026-06-01T14:00:00Z",
        updatedAt: "2026-07-01T15:00:00Z",
        tags: ["Fedwire", "High Value", "Liquidity"],
        dataset: "Payment Transactions",
        schedule: { type: "Scheduled", frequency: "Monthly", startDate: "2026-06-01", runTime: "23:59", timezone: "EST", delivery: "Download", retention: "Forever" },
        filters: [{ field: "amount", operator: ">", value: 1000000 }],
        selectedFields: ["transaction_id", "sender_account", "receiver_account", "amount", "settlement_date"]
    },
    {
        id: "RPT-004",
        reportName: "ACH Returns Weekly",
        description: "Weekly summary of ACH return codes and affected transactions.",
        author: "Emma Wilson",
        visibility: "public",
        category: "Exceptions",
        paymentRail: "ACH",
        regulatoryBody: "NACHA",
        region: "US",
        frequency: "Weekly",
        reportStatus: "published",
        version: "3.0",
        createdAt: "2026-05-10T10:00:00Z",
        updatedAt: "2026-07-10T12:00:00Z",
        tags: ["ACH", "Returns", "Weekly"],
        dataset: "Exceptions",
        schedule: { type: "Scheduled", frequency: "Weekly", startDate: "2026-05-10", runTime: "08:00", timezone: "EST", delivery: "Save to Report Center", retention: "90 days" },
        filters: [],
        selectedFields: ["return_code", "transaction_id", "amount", "original_date"]
    },
    {
        id: "RPT-005",
        reportName: "SCT Inst SLA Breaches",
        description: "Monitor SEPA Instant transactions that exceeded the 10-second processing SLA.",
        author: "David Johnson",
        visibility: "private",
        category: "Payment Transactions",
        paymentRail: "SCT Inst",
        regulatoryBody: "EPC",
        region: "Europe",
        frequency: "Ad Hoc",
        reportStatus: "published",
        version: "1.0",
        createdAt: "2026-07-22T08:00:00Z",
        updatedAt: "2026-07-22T08:00:00Z",
        tags: ["SCT Inst", "SLA", "Ad Hoc"],
        dataset: "Payment Transactions",
        schedule: { type: "Ad Hoc" },
        filters: [{ field: "processing_time_ms", operator: ">", value: 10000 }],
        selectedFields: ["transaction_id", "processing_time_ms", "amount", "sender_bank"]
    },
    {
        id: "RPT-006",
        reportName: "SDD Core Mandate Status",
        description: "Active and revoked SEPA Direct Debit Core mandates overview.",
        author: "Rahul Mehta",
        visibility: "public",
        category: "Entitlements",
        paymentRail: "SDD Core",
        regulatoryBody: "EPC",
        region: "Europe",
        frequency: "Monthly",
        reportStatus: "published",
        version: "1.1",
        createdAt: "2026-01-15T09:00:00Z",
        updatedAt: "2026-06-15T11:00:00Z",
        tags: ["SDD", "Mandates"],
        dataset: "Entitlements",
        schedule: { type: "Scheduled", frequency: "Monthly", startDate: "2026-01-15", runTime: "02:00", timezone: "CET", delivery: "Save to Report Center", retention: "90 days" },
        filters: [],
        selectedFields: ["mandate_id", "status", "debtor_name", "creditor_name"]
    },
    {
        id: "RPT-007",
        reportName: "System Users Access Audit",
        description: "Quarterly audit of user roles, access levels, and last login times.",
        author: "Ananya Sharma",
        visibility: "private",
        category: "Users",
        paymentRail: "System",
        regulatoryBody: "Internal Audit",
        region: "Global",
        frequency: "Quarterly",
        reportStatus: "published",
        version: "4.0",
        createdAt: "2025-12-01T10:00:00Z",
        updatedAt: "2026-07-01T10:00:00Z",
        tags: ["Audit", "Users", "Security"],
        dataset: "Users",
        schedule: { type: "Scheduled", frequency: "Quarterly", startDate: "2026-01-01", runTime: "00:00", timezone: "UTC", delivery: "Download", retention: "Forever" },
        filters: [],
        selectedFields: ["user_id", "role", "last_login", "status"]
    }
];
